### ISSUE TITLE
Wullean fork

### ISSUE THREAD

**Issue by koko777888** [Helco/zzio#258]
I am trying to make an edit in Zanzarah .scn files(triggers specifically). To do that:

1. I downloaded Wullean fork which has a save button option
2. compiled it.
3. downloaded your zzre-win-x64.zip from Releases
4. unpacked it and followed instructions - placed Zzre folder in ZanZarah folder near System folder
5. The compiled version of Wullen fork does not have zzre.exe file!
6. So as I understand I simply need to copy/paste it in Zzre folder
7. But I after I do that I zzre.exe doesnt launch and the editor wont open!

Please help! Im not a developer or a coder. I dont understant what I need o do. Can you please tell me what am i doing wrong and what needs to be done?

**Comment by Helco** [comment]
The instructions are for developers to create a development build which is not the same as a release build (this is why there is no zzre.exe directly in the zzre folder). For this one time I built and uploaded a release build of the Wullean fork for you: [wullean-zzre-win-x64.zip](https://github.com/Helco/zzio/files/13040789/wullean-zzre-win-x64.zip)

However: also the Wullean fork seem to currently only support changing and duplicating trigger and FOModel positions so for any serious mod development this *will not suffice*.

This project is still **very** early in development (despite its age) and most user-facing features are not ready, which is why there is no general release for users and only developer instructions. I will not support the Wullean fork going forward and probably not developing mod creation soon.

**Comment by koko777888** [comment]
Thank You!
